controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster

wheel_velocity_controller:
  ros__parameters:
    type: forward_command_controller/ForwardCommandController
    joints:
      - front_wheel_joint
      - right_wheel_joint
      - left_wheel_joint
    interface_name: velocity
